"""
Shuki setup utility.

Run this once after downloading all files to the same directory.
It creates the required folder structure and moves everything into place.

Usage:
    python setup.py                        # install to current directory
    python setup.py --dir C:\\codex        # install to a specific directory
    python setup.py --dry-run             # preview without making changes
"""
import argparse
import os
import shutil
import sys
from pathlib import Path


# ── File map: filename (as downloaded) → relative destination ─────────────────
#
# Destination is relative to the chosen install root.
# Files not listed here are ignored (e.g. setup.py itself).

FILE_MAP = {
    # Core agent package
    "main.py":              "main.py",
    "config.py":            "config.py",
    "requirements.txt":     "requirements.txt",
    "README.md":            "README.md",

    # agent/ package
    "__init__.py":          "agent/__init__.py",
    "context.py":           "agent/context.py",
    "graph.py":             "agent/graph.py",
    "llm_client.py":        "agent/llm_client.py",
    "nodes.py":             "agent/nodes.py",
    "rules.py":             "agent/rules.py",
    "skills.py":            "agent/skills.py",
    "state.py":             "agent/state.py",
    "tool_selector.py":     "agent/tool_selector.py",

    # tools/ package (now under .shuki/)
    "code_tools.py":        ".shuki/tools/code_tools.py",

    # Bundled skills (now under .shuki/skill/)
    "coding.md":            ".shuki/skill/coding.md",
    "testing.md":           ".shuki/skill/testing.md",
    "documentation.md":     ".shuki/skill/documentation.md",
    "devops.md":            ".shuki/skill/devops.md",

    # Example rules (under .shuki/rules/)
    "no_print_statements.md":   ".shuki/rules/no_print_statements.md",
    "always_type_hints.md":     ".shuki/rules/always_type_hints.md",
    "prefer_pathlib.md":        ".shuki/rules/prefer_pathlib.md",
}

# Files that need an empty __init__.py created alongside them
PACKAGE_DIRS = ["agent", ".shuki", ".shuki/tools"]

# Directories to create under install_dir/.shuki/ (local config dirs)
SHUKI_SUBDIRS = ["rules", "skill"]


# ── Helpers ───────────────────────────────────────────────────────────────────

def _localappdata() -> Path:
    base = os.environ.get("LOCALAPPDATA") or os.path.expanduser("~")
    return Path(base)


def _print(msg: str, dry_run: bool = False):
    prefix = "[DRY RUN] " if dry_run else ""
    print(prefix + msg)


def _mkdir(path: Path, dry_run: bool):
    if path.exists():
        return
    _print(f"  mkdir  {path}", dry_run)
    if not dry_run:
        path.mkdir(parents=True, exist_ok=True)


def _move(src: Path, dst: Path, dry_run: bool):
    if src.resolve() == dst.resolve():
        _print(f"  skip  {src.name:35s} (already in place)", dry_run)
        return
    _print(f"  move  {src.name:35s} → {dst}", dry_run)
    if not dry_run:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(src, dst)


def _touch_init(pkg_dir: Path, dry_run: bool):
    init = pkg_dir / "__init__.py"
    if not init.exists():
        _print(f"  touch  {init}", dry_run)
        if not dry_run:
            pkg_dir.mkdir(parents=True, exist_ok=True)
            init.write_text("# auto-generated by setup.py\n")


# ── Main setup ────────────────────────────────────────────────────────────────

def setup(source_dir: Path, install_dir: Path, dry_run: bool):
    print(f"\nShuki Setup")
    print(f"  Source  : {source_dir}")
    print(f"  Install : {install_dir}")
    print(f"  Shuki   : {_localappdata() / '.shuki'}")
    if dry_run:
        print("  Mode    : DRY RUN (no changes will be made)")
    print()

    # 1. Create install directory
    _mkdir(install_dir, dry_run)

    # 2. Place each known file
    unrecognised = []
    placed = []

    for src_path in sorted(source_dir.iterdir()):
        if src_path.name == "setup.py" or src_path.is_dir():
            continue
        if src_path.suffix not in (".py", ".md", ".txt"):
            continue

        dst_rel = FILE_MAP.get(src_path.name)
        if dst_rel is None:
            unrecognised.append(src_path.name)
            continue

        dst_path = install_dir / dst_rel
        _move(src_path, dst_path, dry_run)
        placed.append(src_path.name)

    # 3. Ensure __init__.py exists in every package dir
    print()
    print("Package init files:")
    for pkg in PACKAGE_DIRS:
        _touch_init(install_dir / pkg, dry_run)

    # 4. Create workspace directory
    workspace = install_dir / "workspace"
    print()
    print("Workspace:")
    _mkdir(workspace, dry_run)

    # 5. Create local .shuki/{rules,skill}
    shuki_root = install_dir / ".shuki"
    print()
    print(f"Local config dirs ({shuki_root}):")
    for sub in SHUKI_SUBDIRS:
        _mkdir(shuki_root / sub, dry_run)

    # 6. Summary
    print()
    print(f"✓ Placed {len(placed)} files")

    if unrecognised:
        print(f"  Skipped (unrecognised): {', '.join(unrecognised)}")

    # 7. Next steps
    if not dry_run:
        _print_next_steps(install_dir)


def _print_next_steps(install_dir: Path):
    shuki = install_dir / ".shuki"
    print(f"""
Next steps
──────────
1. Install dependencies:
       cd {install_dir}
       pip install -r requirements.txt

2. Configure your LLM (add to your profile or run before launching):
       $env:LLM_BASE_URL = "http://your-server:11434"
       $env:LLM_MODEL    = "llama3"
       $env:WORKSPACE_ROOT = "{install_dir / 'workspace'}"

3. (Optional) Add your coding rules:
       # Copy example rules to activate them:
       copy "{shuki / 'rules' / '*'}" "{shuki / 'rules'}\\"

       # Or write your own — one .md file per rule:
       notepad "{shuki / 'rules' / 'my_rule.md'}"

4. (Optional) Add custom skills to:
       {shuki / 'skill'}

5. Run:
       cd {install_dir}
       python main.py
""")


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Shuki setup — organise downloaded files into the correct structure"
    )
    parser.add_argument(
        "--dir", "-d",
        default=str(Path.cwd()),
        help="Install directory (default: current directory)",
    )
    parser.add_argument(
        "--source", "-s",
        default=str(Path(__file__).parent),
        help="Source directory where files were downloaded (default: same dir as setup.py)",
    )
    parser.add_argument(
        "--dry-run", "-n",
        action="store_true",
        help="Preview actions without making any changes",
    )
    args = parser.parse_args()

    source_dir  = Path(args.source).resolve()
    install_dir = Path(args.dir).resolve()

    if not source_dir.exists():
        print(f"Error: source directory not found: {source_dir}", file=sys.stderr)
        sys.exit(1)

    setup(source_dir, install_dir, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
